config/routes.rb
Autobase::Application.routes.draw do
  
  resources :role_types

  resources :commission_structures

  resources :commission_plans

  resources :dealer_user_roles

  resources :address_suppliers

  resources :model_year_trims

  resources :model_years

  resources :appraisal_point_types

  resources :appraisal_users

  resources :book_values

  resources :appraisal_points

  resources :valuations

  resources :appraisals

  resources :base_rate_types

  resources :operands

  resources :metrics

  resources :reporting_categories

  resources :operation_types

  resources :dealer_metrics

  resources :metric_users

  resources :period_values

  resources :seasonality_types

  resources :seasonalities

  resources :targets

  resources :quote_types

  resources :proposals

  resources :proposal_statuses

  resources :quotes

  resources :comments

  resources :constraint_types

  resources :constraints

  resources :base_rates

  resources :fee_types

  resources :fees

  resources :qualification_requirements

  resources :volume_bonus_plans

  resources :funding_types

  resources :funding_plans

  resources :currencies

  resources :financial_transaction_types

  resources :financial_transactions

  resources :dealer_tax_rates

  resources :tax_rate_types

  resources :tax_rates

  resources :feature_types

  resources :features

  resources :registration_marks

  resources :mileage_readings

  resources :trims

  resources :models

  resources :makes

  resources :vehicles

  resources :purchase_types

  resources :purchases

  resources :referral_types

  resources :referrals

  resources :roles

  resources :sale_users

  resources :product_types

  resources :sale_types

  resources :products

  get '/sales/validate_unique_email'
  get '/sales/validate_unique_phone_no'
  resources :sales

  resources :events

  resources :contact_number_types

  resources :contact_numbers

  resources :emails

  resources :employment_types

  resources :income_types

  resources :incomes

  resources :employments

  resources :employers

  resources :address_customers

  resources :customer_types

  resources :customers

  resources :name_numbers

  resources :postcodes

  resources :streets

  resources :states

  resources :addresses
  
  resources :permissions

  resources :suppliers

  resources :preference_types

  resources :preferences

  resources :dealers
  
  devise_for :users

  root :to => "sales#index"

end

app/models/qualification_requirement.rb
class QualificationRequirement < ActiveRecord::Base
  attr_accessible :value, :metric_id
  
  belongs_to :metric
  
  has_many :qualification_requirement_volume_bonus_plans
  has_many :qualification_requirements, :through => :qualification_requirement_volume_bonus_plans
  
end

app/controllers/qualification_requirements_controller.rb
class QualificationRequirementsController < ApplicationController
  load_and_authorize_resource
  
  def index
  end

  def show
  end

  def new
  end

  def create
    if @qualification_requirement.save
      redirect_to @qualification_requirement, :notice => "Successfully created qualification requirement."
    else
      render :action => 'new'
    end
  end

  def edit
  end

  def update
    if @qualification_requirement.update_attributes(params[:qualification_requirement])
      redirect_to @qualification_requirement, :notice  => "Successfully updated qualification requirement."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @qualification_requirement.destroy
    redirect_to qualification_requirements_url, :notice => "Successfully destroyed qualification requirement."
  end
end

app/helpers/qualification_requirements_helper.rb
module QualificationRequirementsHelper
end

app/views/qualification_requirements/_form.html.erb
  <div class="group">
    <%= f.label :value, t("activerecord.attributes.qualification_requirement.value", :default => "Value"), :class => :label %>
    <%= f.text_field :value, :class => 'text_field' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :metric_id, t("activerecord.attributes.qualification_requirement.metric_id", :default => "Metric"), :class => :label %>
    <%= f.number_field :metric_id, :class => 'number_field' %>
    <span class="description">Ex: a simple text</span>
  </div>
<div class="group navform wat-cf">
  <button class="button" type="submit">
    <%= image_tag("web-app-theme/icons/tick.png", :alt => "#{t("web-app-theme.save", :default => "Save")}") %> <%= t("web-app-theme.save", :default => "Save") %>
  </button>
  <span class="text_button_padding"><%= t("web-app-theme.or", :default => "or") %></span>
	<%= link_to t("web-app-theme.cancel", :default => "Cancel"), qualification_requirements_path, :class => "text_button_padding link_button" %>
</div>

app/views/qualification_requirements/edit.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", qualification_requirements_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_qualification_requirement_path %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_qualification_requirement_path %></li>
    </ul>
  </div>
  <div class="content">
    <h2 class="title"><%= t("web-app-theme.edit", :default => "Edit") %> QualificationRequirement</h2>
    <div class="inner">
      <%= form_for @qualification_requirement, :url => qualification_requirement_path(@qualification_requirement), :html => { :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

app/views/qualification_requirements/index.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first active"><%= link_to "#{t("web-app-theme.list", :default => "List")}", qualification_requirements_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_qualification_requirement_path %></li>
    </ul>
  </div>
  <div class="content">
    <h2 class="title"><%= t("web-app-theme.all", :default => "All")  %> QualificationRequirements</h2>
    <div class="inner">
      <table class="table">
        <tr>
          <th class="first">ID</th>
                    <th>
            <%= t("activerecord.attributes.qualification_requirement.value", :default => t("activerecord.labels.value", :default => "Value")) %>
          </th>
                    <th><%= t("web-app-theme.created_at", :default => "Created at")  %></th>
          <th class="last">&nbsp;</th>
        </tr>
        <% @qualification_requirements.each do |qualification_requirement| -%>
        <tr class="<%= cycle("odd", "even") %>">
          <td>
            <%= qualification_requirement.id %>
          </td>
                    <td>
            <%= link_to qualification_requirement.value, qualification_requirement_path(qualification_requirement) %>
          </td>
                    <td>
            <%= qualification_requirement.created_at %>
          </td>
          <td class="last">
            <%= link_to "#{t("web-app-theme.show", :default => "Show")}", qualification_requirement_path(qualification_requirement) %> |
            <%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_qualification_requirement_path(qualification_requirement) %> |
            <%= link_to "#{t("web-app-theme.delete", :default => "Delete")}", qualification_requirement_path(qualification_requirement), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
          </td>
        </tr>
        <% end -%>
      </table>
      <div class="actions-bar wat-cf">
        <div class="actions">
        </div>
        
      </div>
    </div>
  </div>
</div>

app/views/qualification_requirements/new.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", qualification_requirements_path  %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_qualification_requirement_path %></li>
    </ul>
  </div>
  <div class="content">
    <h2 class="title"><%= t("web-app-theme.new", :default => "New")%>  QualificationRequirement</h2>
    <div class="inner">
      <%= form_for :qualification_requirement, :url => qualification_requirements_path, :html => { :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

app/views/qualification_requirements/show.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", qualification_requirements_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_qualification_requirement_path %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.show", :default => "Show")}", qualification_requirement_path %></li>
    </ul>
  </div>
  <div class="content">
    <div class="inner">
      
        <p>
          <b><%= t("activerecord.attributes.qualification_requirement.value", :default => t("activerecord.labels.value", :default => "Value")) %>:</b>
          <%= @qualification_requirement.value %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.qualification_requirement.metric_id", :default => t("activerecord.labels.metric_id", :default => "Metric")) %>:</b>
          <%= @qualification_requirement.metric_id %>
        </p>
      <div class="wat-cf">
        <%= link_to image_tag("web-app-theme/icons/application_edit.png", :alt => "#{t("web-app-theme.edit", :default=> "Edit")}") + " " + t("web-app-theme.edit", :default=> "Edit"), edit_qualification_requirement_path(@qualification_requirement), :class => "button" %>
        <%= link_to image_tag("web-app-theme/icons/cross.png", :alt => "#{t("web-app-theme.delete", :default=> "Delete")}") + " " + t("web-app-theme.delete", :default => "Delete"), qualification_requirement_path(@qualification_requirement), :method => "delete", :class => "button", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
      </div>
    </div>
  </div>
</div>