config/routes.rb
Autobase::Application.routes.draw do
  
  resources :role_types

  resources :commission_structures

  resources :commission_plans

  resources :dealer_user_roles

  resources :address_suppliers

  resources :model_year_trims

  resources :model_years

  resources :appraisal_point_types

  resources :appraisal_users

  resources :book_values

  resources :appraisal_points

  resources :valuations

  resources :appraisals

  resources :base_rate_types

  resources :operands

  resources :metrics

  resources :reporting_categories

  resources :operation_types

  resources :dealer_metrics

  resources :metric_users

  resources :period_values

  resources :seasonality_types

  resources :seasonalities

  resources :targets

  resources :quote_types

  resources :proposals

  resources :proposal_statuses

  resources :quotes

  resources :comments

  resources :constraint_types

  resources :constraints

  resources :base_rates

  resources :fee_types

  resources :fees

  resources :qualification_requirements

  resources :volume_bonus_plans

  resources :funding_types

  resources :funding_plans

  resources :currencies

  resources :financial_transaction_types

  resources :financial_transactions

  resources :dealer_tax_rates

  resources :tax_rate_types

  resources :tax_rates

  resources :feature_types

  resources :features

  resources :registration_marks

  resources :mileage_readings

  resources :trims

  resources :models

  resources :makes

  resources :vehicles

  resources :purchase_types

  resources :purchases

  resources :referral_types

  resources :referrals

  resources :roles

  resources :sale_users

  resources :product_types

  resources :sale_types

  resources :products

  get '/sales/validate_unique_email'
  get '/sales/validate_unique_phone_no'
  resources :sales

  resources :events

  resources :contact_number_types

  resources :contact_numbers

  resources :emails

  resources :employment_types

  resources :income_types

  resources :incomes

  resources :employments

  resources :employers

  resources :address_customers

  resources :customer_types

  resources :customers

  resources :name_numbers

  resources :postcodes

  resources :streets

  resources :states

  resources :addresses
  
  resources :permissions

  resources :suppliers

  resources :preference_types

  resources :preferences

  resources :dealers
  
  devise_for :users

  root :to => "sales#index"

end

app/models/currency.rb
class Currency < ActiveRecord::Base
  attr_accessible :value
  
  has_many :financial_transactions
  has_many :product_quotes
  has_many :product_sales
  has_many :incomes
  
end

app/controllers/currencies_controller.rb
class CurrenciesController < ApplicationController
  load_and_authorize_resource
  
  def index
  end

  def show
  end

  def new
  end

  def create
    if @currency.save
      redirect_to @currency, :notice => "Successfully created currency."
    else
      render :action => 'new'
    end
  end

  def edit
  end

  def update
    if @currency.update_attributes(params[:currency])
      redirect_to @currency, :notice  => "Successfully updated currency."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @currency.destroy
    redirect_to currencies_url, :notice => "Successfully destroyed currency."
  end
end

app/helpers/currencies_helper.rb
module CurrenciesHelper
end

app/views/currencies/_form.html.erb
  <div class="group">
    <%= f.label :value, t("activerecord.attributes.currency.value", :default => "Value"), :class => :label %>
    <%= f.text_field :value, :class => 'text_field' %>
    <span class="description">Ex: a simple text</span>
  </div>
<div class="group navform wat-cf">
  <button class="button" type="submit">
    <%= image_tag("web-app-theme/icons/tick.png", :alt => "#{t("web-app-theme.save", :default => "Save")}") %> <%= t("web-app-theme.save", :default => "Save") %>
  </button>
  <span class="text_button_padding"><%= t("web-app-theme.or", :default => "or") %></span>
	<%= link_to t("web-app-theme.cancel", :default => "Cancel"), currencies_path, :class => "text_button_padding link_button" %>
</div>

app/views/currencies/edit.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", currencies_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_currency_path %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_currency_path %></li>
    </ul>
  </div>
  <div class="content">
    <h2 class="title"><%= t("web-app-theme.edit", :default => "Edit") %> Currency</h2>
    <div class="inner">
      <%= form_for @currency, :url => currency_path(@currency), :html => { :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

app/views/currencies/index.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first active"><%= link_to "#{t("web-app-theme.list", :default => "List")}", currencies_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_currency_path %></li>
    </ul>
  </div>
  <div class="content">
    <h2 class="title"><%= t("web-app-theme.all", :default => "All")  %> Currencies</h2>
    <div class="inner">
      <table class="table">
        <tr>
          <th class="first">ID</th>
                    <th>
            <%= t("activerecord.attributes.currency.value", :default => t("activerecord.labels.value", :default => "Value")) %>
          </th>
                    <th><%= t("web-app-theme.created_at", :default => "Created at")  %></th>
          <th class="last">&nbsp;</th>
        </tr>
        <% @currencies.each do |currency| -%>
        <tr class="<%= cycle("odd", "even") %>">
          <td>
            <%= currency.id %>
          </td>
                    <td>
            <%= link_to currency.value, currency_path(currency) %>
          </td>
                    <td>
            <%= currency.created_at %>
          </td>
          <td class="last">
            <%= link_to "#{t("web-app-theme.show", :default => "Show")}", currency_path(currency) %> |
            <%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_currency_path(currency) %> |
            <%= link_to "#{t("web-app-theme.delete", :default => "Delete")}", currency_path(currency), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
          </td>
        </tr>
        <% end -%>
      </table>
      <div class="actions-bar wat-cf">
        <div class="actions">
        </div>
        
      </div>
    </div>
  </div>
</div>

app/views/currencies/new.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", currencies_path  %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_currency_path %></li>
    </ul>
  </div>
  <div class="content">
    <h2 class="title"><%= t("web-app-theme.new", :default => "New")%>  Currency</h2>
    <div class="inner">
      <%= form_for :currency, :url => currencies_path, :html => { :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

app/views/currencies/show.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", currencies_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_currency_path %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.show", :default => "Show")}", currency_path %></li>
    </ul>
  </div>
  <div class="content">
    <div class="inner">
      
        <p>
          <b><%= t("activerecord.attributes.currency.value", :default => t("activerecord.labels.value", :default => "Value")) %>:</b>
          <%= @currency.value %>
        </p>
      <div class="wat-cf">
        <%= link_to image_tag("web-app-theme/icons/application_edit.png", :alt => "#{t("web-app-theme.edit", :default=> "Edit")}") + " " + t("web-app-theme.edit", :default=> "Edit"), edit_currency_path(@currency), :class => "button" %>
        <%= link_to image_tag("web-app-theme/icons/cross.png", :alt => "#{t("web-app-theme.delete", :default=> "Delete")}") + " " + t("web-app-theme.delete", :default => "Delete"), currency_path(@currency), :method => "delete", :class => "button", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
      </div>
    </div>
  </div>
</div>