config/routes.rb
Autobase::Application.routes.draw do
  
  resources :role_types

  resources :commission_structures

  resources :commission_plans

  resources :dealer_user_roles

  resources :address_suppliers

  resources :model_year_trims

  resources :model_years

  resources :appraisal_point_types

  resources :appraisal_users

  resources :book_values

  resources :appraisal_points

  resources :valuations

  resources :appraisals

  resources :base_rate_types

  resources :operands

  resources :metrics

  resources :reporting_categories

  resources :operation_types

  resources :dealer_metrics

  resources :metric_users

  resources :period_values

  resources :seasonality_types

  resources :seasonalities

  resources :targets

  resources :quote_types

  resources :proposals

  resources :proposal_statuses

  resources :quotes

  resources :comments

  resources :constraint_types

  resources :constraints

  resources :base_rates

  resources :fee_types

  resources :fees

  resources :qualification_requirements

  resources :volume_bonus_plans

  resources :funding_types

  resources :funding_plans

  resources :currencies

  resources :financial_transaction_types

  resources :financial_transactions

  resources :dealer_tax_rates

  resources :tax_rate_types

  resources :tax_rates

  resources :feature_types

  resources :features

  resources :registration_marks

  resources :mileage_readings

  resources :trims

  resources :models

  resources :makes

  resources :vehicles

  resources :purchase_types

  resources :purchases

  resources :referral_types

  resources :referrals

  resources :roles

  resources :sale_users

  resources :product_types

  resources :sale_types

  resources :products

  get '/sales/validate_unique_email'
  get '/sales/validate_unique_phone_no'
  resources :sales

  resources :events

  resources :contact_number_types

  resources :contact_numbers

  resources :emails

  resources :employment_types

  resources :income_types

  resources :incomes

  resources :employments

  resources :employers

  resources :address_customers

  resources :customer_types

  resources :customers

  resources :name_numbers

  resources :postcodes

  resources :streets

  resources :states

  resources :addresses
  
  resources :permissions

  resources :suppliers

  resources :preference_types

  resources :preferences

  resources :dealers
  
  devise_for :users

  root :to => "sales#index"

end

app/models/sale.rb
class Sale < ActiveRecord::Base
  attr_accessible :dealer_id, :customer_id, :date, :sale_type_id, :customer_attributes, :sale_vehicles_attributes,
                  :products_attributes, :product_sales_attributes, :comments_attributes, :roles_attributes,
                  :funding_plan_sales_attributes
  
  belongs_to :dealer
  belongs_to :customer
  belongs_to :sale_type
  
  has_many :comments, :as => :comment_originator
  
  has_many :product_sales
  has_many :products, :through => :product_sales
  
  has_many :roles, :as => :role_originator
  has_many :users, :through => :roles
  
  has_many :sale_vehicles
  has_many :vehicles, :through => :sale_vehicles
  
  has_many :funding_plan_sales
  has_many :funding_plans, :through => :funding_plan_sales
  has_many :financial_transaction_funding_plan_sales, :through => :funding_plan_sales
  has_many :financial_transactions, :through => :financial_transaction_funding_plan_sales
  
  accepts_nested_attributes_for :customer, :reject_if => :all_blank
  accepts_nested_attributes_for :sale_vehicles, :reject_if => :all_blank
  accepts_nested_attributes_for :product_sales, :allow_destroy => true, :reject_if => :all_blank
  accepts_nested_attributes_for :products, :allow_destroy => true, :reject_if => :all_blank
  accepts_nested_attributes_for :comments, :allow_destroy => true, :reject_if => :all_blank
  accepts_nested_attributes_for :roles, :allow_destroy => true, :reject_if => :all_blank
  accepts_nested_attributes_for :funding_plan_sales, :allow_destroy => true, :reject_if => :all_blank
  
  validates :customer, :presence => true
  validates :sale_type, :presence => true
  validates :date, :presence => true
  validate :must_have_at_least_one_vehicle_or_product
  validate :total_amount_funded_must_equal_total_price
  
  def must_have_at_least_one_vehicle_or_product
    if (sale_vehicles.length + product_sales.length) == 0
      errors.add(:vehicles, " or product must exist!")
      errors.add(:products, " or vehicle must exist!")
    end
  end
  
  def total_amount_funded_must_equal_total_price
    if( total_amount_funded != total_price )
      errors.add(:base, "Amount funded (#{total_amount_funded}) must be equal to total price (#{total_price}).")
    end
  end
  
  def total_amount_funded
    funding_plan_sales.sum(:amount)
  end
  
  def total_price
    sale_vehicles.sum(:price) + product_sales.sum(:price)
  end
  
end

app/models/sale_type.rb
class SaleType < ActiveRecord::Base
  attr_accessible :value
  
  has_many :sales
  
  has_many :dealer_sale_types
  has_many :dealers, :through => :dealer_sale_types
  
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  load_and_authorize_resource :except => [:create, :update]
  before_filter :load_select_values, :only => [:new, :edit, :create, :update]
  
  protect_from_forgery :except=>[ :validate_unique_email,:validate_unique_phone_no ]

  def load_select_values
    @makes = Make.accessible_by(current_ability)
    @sale_types = SaleType.accessible_by(current_ability)
    @customer_types = CustomerType.accessible_by(current_ability)
    @users = User.accessible_by(current_ability)
    @role_types = RoleType.accessible_by(current_ability)
    @funding_types = FundingType.accessible_by(current_ability)
    @tax_rates = TaxRate.accessible_by(current_ability)
    @product_types = ProductType.accessible_by(current_ability)
  end
  
  def index
    # @sales is already loaded via load_and_authorize_resource
  end

  def show
  end

  def new
    current_ability.attributes_for(:new, Sale).each do |key, value|
      @sale.send("#{key}=", value)
    end
    @sale.build_customer
    @sale.customer.emails.build
    @sale.customer.addresses.build
    contact_numbers_to_build = ["Home", "Work", "Mobile"]
    contact_numbers_to_build.each do |number_type|
      @built_contact_number = @sale.customer.contact_numbers.build
      @built_contact_number.contact_number_type = ContactNumberType.where(:value => number_type).first
    end
    @sale.product_sales.build
    @sale.roles.build
    @sale.funding_plan_sales.build
    @built_sale_vehicle = @sale.sale_vehicles.build
    @built_vehicle = @built_sale_vehicle.build_vehicle
    @built_vehicle.registration_marks.build
    @sale.attributes = params[:sale]
    
  end

  def create
    @sale = Sale.new
    authorize! :create, @sale
    current_ability.attributes_for(:new, Sale).each do |key, value|
      @sale.send("#{key}=", value)
    end
    if !params[:sale][:sale_vehicles_attributes].blank?
      params[:sale][:sale_vehicles_attributes].each { |key,value|
        if !value[:vehicle_attributes].blank?
          value[:vehicle_attributes].delete(:make)
          value[:vehicle_attributes].delete(:model)
        end
      }
    end
    if !params[:sale][:funding_plan_sales_attributes].blank?
      params[:sale][:funding_plan_sales_attributes].each { |key,value|
        value.delete(:funding_type)
        value.delete(:supplier)
      }
    end
    @sale.attributes = params[:sale]
    if @sale.save
      notice_message = '<div class="alert alert-success">Sale was created successfully</div>'
      redirect_to @sale, :notice => notice_message.html_safe
    else
      error_message = '<div class="alert alert-error">' + @sale.errors.full_messages.join('</div><div class="alert alert-error">') + '</div>'
      flash[:error] = error_message.html_safe if @sale.errors.any?
      render :action => 'new'
    end
  end

  def edit
    @sale.build_customer if @sale.customer.blank?
    @sale.customer.emails.build if @sale.customer.emails.blank?
    @sale.customer.addresses.build if @sale.customer.addresses.blank?
    contact_numbers_to_build = ["Home", "Work", "Mobile"]
    contact_numbers_to_build.each do |number_type|
      if @sale.customer.contact_numbers.where(:contact_number_type_id => ContactNumberType.where(:value => number_type)).blank?
        @built_contact_number = @sale.customer.contact_numbers.build
        @built_contact_number.contact_number_type = ContactNumberType.where(:value => number_type).first
      end
    end
    @sale.sale_vehicles.build if @sale.sale_vehicles.blank?
    @sale.sale_vehicles.each do |sale_vehicle|
        sale_vehicle.build_vehicle if sale_vehicle.vehicle.blank?
        sale_vehicle.vehicle.registration_marks.build if sale_vehicle.vehicle.registration_marks.blank?
    end
    @sale.roles.build if @sale.roles.blank?
    @sale.product_sales.build if @sale.product_sales.blank?
    @sale.funding_plan_sales.build if @sale.funding_plan_sales.blank?
  end

  def update
    @sale = Sale.find(params[:id])
    authorize! :update, @sale
    current_ability.attributes_for(:new, Sale).each do |key, value|
      @sale.send("#{key}=", value)
    end
    if !params[:sale][:sale_vehicles_attributes].blank?
      params[:sale][:sale_vehicles_attributes].each { |key,value|
        if !value[:vehicle_attributes].blank?
          value[:vehicle_attributes].delete(:make)
          value[:vehicle_attributes].delete(:model)
        end
      }
    end
    if !params[:sale][:funding_plan_sales_attributes].blank?
      params[:sale][:funding_plan_sales_attributes].each { |key,value|
        value.delete(:funding_type)
        value.delete(:supplier)
      }
    end
    if @sale.update_attributes(params[:sale])
      redirect_to @sale, :notice  => "Successfully updated sale."
    else
      error_message = '<div class="alert alert-error">' + @sale.errors.full_messages.join('</div><div class="alert alert-error">') + '</div>'
      flash[:error] = error_message.html_safe if @sale.errors.any?
      render :action => 'edit'
    end
  end

  def destroy
    @sale.destroy
    redirect_to sales_url, :notice => "Successfully destroyed sale."
  end

  def validate_unique_email
    if Email.where(:value=>params[:fieldValue]).length == 0
      render :json=> [params[:fieldId],true]
    else
      render :json=> [params[:fieldId],false]
    end
  end

  def validate_unique_phone_no 
    if ContactNumber.where(:value=>params[:fieldValue]).length == 0
      render :json=> [params[:fieldId],true]
    else
      render :json=> [params[:fieldId],false]
    end
  end
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/sales/_form.html.erb
<div class="row">
	<div class="span6">
		<div class="nonboxy-widget">
			<div class="widget-head">
				<h5>Details</h5>
			</div>
			<div class="widget-content">
				<div class="widget-box">
					<div class = 'form-horizontal'>
						<fieldset>
							<legend>Sale Details</legend>
							<div class="control-group">
								<label class="control-label">Sale Type</label>
								<div class="controls">
									<%= sale.collection_select(:sale_type_id, @sale_types, :id, :value, {:prompt => ""}, {:class => "chzn-select", "data-placeholder" => "Select Sale Type"}) %>
								</div>
							</div>
							<div class="control-group">
								<label class="control-label">Date of Sale</label>
								<div class="controls">
									<%= sale.text_field :date, :class => 'date' %>
								</div>
							</div>
						</fieldset>
					</div>
				</div>
			</div>
			<div class="widget-head">
				<h5>Customer</h5>
			</div>
			<div class="widget-content">
				<div class="widget-box cocoon">
					<div class = 'form-horizontal customer-features'>
						<%= sale.fields_for :customer do |customer_builder| %>
				  			<fieldset>
								<legend>Customer Details</legend>
								<%= render :partial => "customers/form", :locals => {:f => customer_builder, :form_actions_visible => false} %>
							</fieldset>
							<fieldset>
								<legend>Customer Emails</legend>
								<%= customer_builder.fields_for :emails do |email| %>
									<%= render :partial => "emails/form", :locals => {:f => email, :form_actions_visible => false} %>
								<% end -%>
								<div class="add-field-links">
									<%= link_to_add_association '<i></i> Add Email'.html_safe, customer_builder, :emails, :partial => 'emails/form', :render_options => {:locals => {:form_actions_visible => 'false', :legend_type => 'Customer'}}, :class => 'btn' %>        
								</div>
							</fieldset>
							<fieldset>
								<legend>Customer Contact Numbers</legend>
								<%= customer_builder.fields_for :contact_numbers do |contact_numbers_builder| %>
									<%= render :partial => "customers/customer_contact_numbers_fixed", :locals => {:f => contact_numbers_builder, :form_actions_visible => false} %>
								<% end -%>
							</fieldset>
							<div class="add-field-links">
								<%= link_to_add_association '<i></i> Add Contact Number'.html_safe, customer_builder, :contact_numbers, :partial => 'contact_numbers/form', :render_options => {:locals => {:form_actions_visible => 'false', :legend_type => 'Customer'}}, :class => 'btn' %>
							</div>
						<% end -%>
					</div>
				</div>
			</div>
			<div class="widget-head">
				<h5>Team</h5>
			</div>
			<div class="widget-content">
				<div class="widget-box cocoon">
					<%= sale.fields_for :roles do |roles_builder| %>
						<%= render :partial => "roles/form", :locals => {:f => roles_builder, :form_actions_visible => false} %>
					<% end -%>
					<div class="add-field-links">
						<%= link_to_add_association '<i></i> Add Team Member'.html_safe, sale, :roles, :partial => 'roles/form', :render_options => {:locals => {:form_actions_visible => 'false'}}, :class => 'btn' %>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="span6">
		<div class="nonboxy-widget">
			<div class="widget-head">
				<h5>Vehicle</h5>
			</div>
			<div class="widget-content">
				<div class="widget-box cocoon">
					<%= sale.fields_for :sale_vehicles do |sale_vehicles_builder| %>
						<%= render :partial => "sale_vehicles/form", :locals => {:f => sale_vehicles_builder, :form_actions_visible => false} %>	
					<% end -%>
					<div class="add-field-links">
						<%= link_to_add_association '<i></i> Add Vehicle'.html_safe, sale, :sale_vehicles, :partial => 'sale_vehicles/form', :render_options => {:locals => {:form_actions_visible => 'false', :show_features => true, :fieldset_label => 'Vehicle Details'}}, :class => 'btn' %>
					</div>
				</div>
			</div>
			<div class="widget-head">
				<h5>Products</h5>
			</div>
			<div class="widget-content">
				<div class="widget-box cocoon">
					<%= sale.fields_for :product_sales do |product_sales_builder| %>
						<%= render :partial => "product_sales/form", :locals => {:f => product_sales_builder, :form_actions_visible => false} %>
					<% end -%>
					<div class="add-field-links">
						<%= link_to_add_association '<i></i> Add Product'.html_safe, sale, :product_sales, :partial => 'product_sales/form', :render_options => {:locals => {:form_actions_visible => 'false' }}, :class => 'btn' %>
					</div>
				</div>
			</div>
			<div class="widget-head">
				<h5>Financial</h5>
			</div>
			<div class="widget-content">
				<div class="widget-box cocoon">
					<%= sale.fields_for :funding_plan_sales do |funding_plan_sales_builder| %>
						<%= render :partial => "funding_plan_sales/form", :locals => {:f => funding_plan_sales_builder, :form_actions_visible => false, :permanent => true} %>
					<% end -%>
					<div class="add-field-links">
						<%= link_to_add_association '<i></i> Add Funding Type'.html_safe, sale, :funding_plan_sales, :partial => "funding_plan_sales/form", :render_options => {:locals => {:form_actions_visible => 'false'}}, :class => 'btn' %>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<% if form_actions_visible == true %>
	<div class="row">
		<div class="span12">
			<%= render :partial => "shared/form_actions" %>
		</div>
	</div>
<% end %>

app/views/sales/edit.html.erb
<div class="container">
	<%= form_for @sale do |sale| -%>
		<%= render :partial => "form", :locals => {:sale => sale, :form_actions_visible => true} %>
	<% end -%>	
</div>

app/views/sales/index.html.erb
<%= render :partial => "shared/tablecontrols" %>
<div id="newpath" data-newpath=<%= new_sale_path -%>></div>
<div class="container">
	<div class="row">
			<div class = "span12">
				<div class="nonboxy-widget">
	    			<div class="widget-head">
						<h5>Sales</h5>
					</div>
      				<table class="data-tbl-simple table table-bordered">
        			<thead>
						<tr>
	          				<th class="hide">
								Edit Link
							</th>
							<th class="hide">
								Delete Link
							</th>
							<th class="first">
								ID
							</th>
	                    	<th>
								Customer
	          				</th>
	                    	<th>
								Vehicle
							</th>
	          				<th>
								Date of Sale
							</th>
	        			</tr>
					</thead>
					<tbody>
        				<% @sales.each do |sale| %>
						<tr class="<%= cycle("odd", "even") %>">
	          				<td>
								<%= edit_sale_path(sale) %>
							</td>
							<td>
								<%= sale_path(sale) %>
							</td>
							<td>
	            				<%= sale.id %>
	          				</td>
	                    	<td>
	            				<% if !sale.customer.blank? %>
									<%= link_to !sale.customer.features.blank? ? sale.customer.features.where(:feature_type_id => FeatureType.where(:value => "First Name(s)").first.id).first.value + " " + sale.customer.features.where(:feature_type_id => FeatureType.where(:value => "Last Name").first.id).first.value : 'N/A', customer_path(sale.customer) %>
								<% else %>
									<%= 'No Customer' %>
								<% end -%>
	          				</td>
	                    	<td>
	            				<% sale.vehicles.each do |vehicle| %>
									<%= link_to !vehicle.trim.blank? ? vehicle.make.value + " " + vehicle.model.value : 'N/A', vehicle_path(vehicle) %>
								<% end -%>
	          				</td>
							<td>
								<%= sale.date %>
							</td>
	        			</tr>
	        			<% end -%>
	        			<%= link_to "New sale", new_sale_path if can? :create, Sale %>
					</tbody>
      			</table>
	    		</div>
			</div>
		</div>
</div>

app/views/sales/new.html.erb
<%= javascript_include_tag "sales_form" %>
<div class="container">
	<%= form_for @sale do |sale| -%>
		<%= render :partial => "form", :locals => {:sale => sale, :form_actions_visible => true} %>
	<% end -%>	
</div>

app/views/sales/show.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", sales_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_sale_path %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.show", :default => "Show")}", sale_path %></li>
    </ul>
  </div>
  <div class="content">
    <div class="inner">
      
        <p>
          <b><%= t("activerecord.attributes.sale.dealer_id", :default => t("activerecord.labels.dealer_id", :default => "Dealer")) %>:</b>
          <%= @sale.dealer_id %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.sale.customer_id", :default => t("activerecord.labels.customer_id", :default => "Customer")) %>:</b>
          <%= @sale.customer_id %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.sale.date", :default => t("activerecord.labels.date", :default => "Date")) %>:</b>
          <%= @sale.date %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.sale.sale_type_id", :default => t("activerecord.labels.sale_type_id", :default => "Sale type")) %>:</b>
          <%= @sale.sale_type_id %>
        </p>
      <div class="wat-cf">
        <%= link_to image_tag("web-app-theme/icons/application_edit.png", :alt => "#{t("web-app-theme.edit", :default=> "Edit")}") + " " + t("web-app-theme.edit", :default=> "Edit"), edit_sale_path(@sale), :class => "button" %>
        <%= link_to image_tag("web-app-theme/icons/cross.png", :alt => "#{t("web-app-theme.delete", :default=> "Delete")}") + " " + t("web-app-theme.delete", :default => "Delete"), sale_path(@sale), :method => "delete", :class => "button", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
      </div>
    </div>
  </div>
</div>